## Part 1: Preprocessing

In [58]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import numpy as np
from tensorflow.keras.models import Model
from tensorflow.keras import layers

#  Import and read the attrition data
attrition_df = pd.read_csv('https://static.bc-edx.com/ai/ail-v-1-0/m19/lms/datasets/attrition.csv')
attrition_df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EnvironmentSatisfaction,HourlyRate,JobInvolvement,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,Sales,1,2,Life Sciences,2,94,3,...,3,1,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,Research & Development,8,1,Life Sciences,3,61,2,...,4,4,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,Research & Development,2,2,Other,4,92,2,...,3,2,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,Research & Development,3,4,Life Sciences,4,56,3,...,3,3,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,Research & Development,2,1,Medical,1,40,3,...,3,4,1,6,3,3,2,2,2,2

In [84]:
attrition_df["Department"].value_counts()

Department
Research & Development    961
Sales                     446
Human Resources            63
Name: count, dtype: int64

In [59]:
# Determine the number of unique values in each column
attrition_df.nunique()

Age                         43
Attrition                    2
BusinessTravel               3
Department                   3
DistanceFromHome            29
Education                    5
EducationField               6
EnvironmentSatisfaction      4
HourlyRate                  71
JobInvolvement               4
JobLevel                     5
JobRole                      9
JobSatisfaction              4
MaritalStatus                3
NumCompaniesWorked          10
OverTime                     2
PercentSalaryHike           15
PerformanceRating            2
RelationshipSatisfaction     4
StockOptionLevel             4
TotalWorkingYears           40
TrainingTimesLastYear        7
WorkLifeBalance              4
YearsAtCompany              37
YearsInCurrentRole          19
YearsSinceLastPromotion     16
YearsWithCurrManager        18
dtype: int64

In [60]:
# Create y_df with the Attrition and Department columns
y_df = attrition_df[['Attrition', 'Department']]

In [61]:
# Create a list of at least 10 column names to use as X data
selected_columns = [
    'Education',
               'Age',
               'DistanceFromHome',
               'JobSatisfaction',
               'OverTime',
               'StockOptionLevel',
               'WorkLifeBalance',
               'YearsAtCompany',
               'YearsSinceLastPromotion',
               'NumCompaniesWorked']



# Create X_df using your selected columns
X_df = attrition_df[selected_columns]


# Show the data types for X_df
X_df.dtypes

Education                   int64
Age                         int64
DistanceFromHome            int64
JobSatisfaction             int64
OverTime                   object
StockOptionLevel            int64
WorkLifeBalance             int64
YearsAtCompany              int64
YearsSinceLastPromotion     int64
NumCompaniesWorked          int64
dtype: object

In [62]:
# Split the data into training and testing sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X_df, y_df, test_size=0.2, random_state=42)

In [63]:
# Convert your X data to numeric data types however you see fit
# Add new code cells as necessary

X_train["OverTime"].value_counts()

OverTime
No     837
Yes    339
Name: count, dtype: int64

In [64]:
X_train

,Education,Age,DistanceFromHome,JobSatisfaction,OverTime,StockOptionLevel,WorkLifeBalance,YearsAtCompany,YearsSinceLastPromotion,NumCompaniesWorked
1097,2,24,21,1,No,3,3,1,0,0
727,2,18,5,4,No,0,3,0,0,1
254,2,29,20,4,No,1,3,3,0,2
1175,3,39,12,2,No,0,3,5,1,4
1341,3,31,20,3,No,1,3,10,0,1
...,...,...,...,...,...,...,...,...,...,...
1130,3,35,28,3,No,2,2,10,6,1
1294,3,41,5,2,No,0,1,3,1,3
860,4,22,3,4,Yes,1,3,0,0,0
1459,2,29,13,2,Yes,1,3,4,0,4
1126,3,50,9,3,Yes,1,3,1,0,4

In [65]:
# Convert the 'OverTime' column to numeric values
from sklearn.preprocessing import OneHotEncoder
OverTime_encoder = OneHotEncoder(sparse_output=False,drop="first") 
OverTime_encoded = OverTime_encoder.fit(X_train[['OverTime']])
X_train["OverTimeencoded"] = OverTime_encoded.transform(np.array(X_train['OverTime']).reshape (-1, 1))
X_test["OverTimeencoded"] = OverTime_encoded.transform(np.array(X_test['OverTime']).reshape (-1, 1))
# Drop the original 'OverTime' column
X_train = X_train.drop(columns=['OverTime'])
X_test = X_test.drop(columns=['OverTime'])

X_train.dtypes

c:\Users\owner\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(
c:\Users\owner\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

Education                    int64
Age                          int64
DistanceFromHome             int64
JobSatisfaction              int64
StockOptionLevel             int64
WorkLifeBalance              int64
YearsAtCompany               int64
YearsSinceLastPromotion      int64
NumCompaniesWorked           int64
OverTimeencoded            float64
dtype: object

In [66]:
# Create a StandardScaler
scaler = StandardScaler()


# Fit the StandardScaler to the training data
X_scaler=scaler.fit(X_train)


# Scale the training and testing data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [67]:
X_train_scaled

array([[-0.86335572, -1.38855944,  1.44039645, ..., -0.67610953,
        -1.05916816, -0.63641018],
       [-0.86335572, -2.04073779, -0.52269928, ..., -0.67610953,
        -0.65943075, -0.63641018],
       [-0.86335572, -0.84507748,  1.31770296, ..., -0.67610953,
        -0.25969335, -0.63641018],
       ...,
       [ 1.06322176, -1.60595222, -0.76808624, ..., -0.67610953,
        -1.05916816,  1.57131364],
       [-0.86335572, -0.84507748,  0.45884859, ..., -0.67610953,
         0.53978146,  1.57131364],
       [ 0.09993302,  1.43754676, -0.03192534, ..., -0.67610953,
         0.53978146,  1.57131364]])

In [68]:
from sklearn.preprocessing import OneHotEncoder

# Create a OneHotEncoder for the Department column
department_encoder = OneHotEncoder(sparse_output=False)

# Fit the encoder to the training data
department_encoder.fit(y_train[['Department']])


# Create two new variables by applying the encoder
# to the training and testing data
y_department_train = department_encoder.transform(y_train[['Department']])
y_department_test = department_encoder.transform(y_test[['Department']])
y_department_train

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
# Create a OneHotEncoder for the Attrition column
attrition_encoder = OneHotEncoder(sparse_output=False)


# Fit the encoder to the training data
attrition_encoder.fit(y_train[['Attrition']])


# Create two new variables by applying the encoder
# to the training and testing data
y_attrition_train = attrition_encoder.transform(y_train[['Attrition']])
y_attrition_test = attrition_encoder.transform(y_test[['Attrition']])
y_attrition_test

array([[1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.]])

## Part 2: Create, Compile, and Train the Model

In [85]:
X_train_scaled.shape[1]

10

In [70]:
# Find the number of columns in the X training data.
num_columns = X_train_scaled.shape[1]


# Create the input layer
input_layer = layers.Input(shape=(num_columns,),name="input_layer")


# Create at least two shared layers
shared_layer_1 = layers.Dense(64, activation='relu', name="shared_layer_1")(input_layer)
shared_layer_2 = layers.Dense(32, activation='relu', name="shared_layer_2")(shared_layer_1)

In [ ]:
# Create a branch for Department
# with a hidden layer and an output layer

# Create the hidden layer
department_hidden = layers.Dense(16, activation='relu', name="department_hidden")(shared_layer_2)


# Create the output layer
department_output = layers.Dense(y_department_train.shape[1], activation='sigmoid', name="department_output")(department_hidden)
#

In [86]:
y_department_train.shape[1]

3

In [72]:
# Create a branch for Attrition
# with a hidden layer and an output layer

# Create the hidden layer
attrition_hidden = layers.Dense(16, activation='relu', name="attrition_hidden")(shared_layer_2)


# Create the output layer
attrition_output = layers.Dense(y_attrition_train.shape[1], activation='sigmoid', name="attrition_output")(attrition_hidden)

In [73]:
# Create the model
model = Model(inputs=input_layer, outputs={"department_output": department_output, "attrition_output": attrition_output})


# Compile the model
model.compile(optimizer='adam', 
              loss={'department_output': 'categorical_crossentropy', 'attrition_output': 'binary_crossentropy'}, 
              metrics={"department_output":'accuracy', "attrition_output":"accuracy"})
              



# Summarize the model
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer         │ (None, 10)        │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_layer_1      │ (None, 64)        │        704 │ input_layer[0][0] │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ shared_layer_2      │ (None, 32)        │      2,080 │ shared_layer_1[0… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_hidden    │ (None, 16)        │        528 │ shared_layer_2[0… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_hidden   │ (None, 16)        │        528 │ shared_layer_2[0… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ attrition_output    │ (None, 2)         │         34 │ attrition_hidden… │
│ (Dense)             │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ department_output   │ (None, 3)         │         51 │ department_hidde… │
│ (Dense)             │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 3,925 (15.33 KB)

 Trainable params: 3,925 (15.33 KB)

 Non-trainable params: 0 (0.00 B)

In [77]:
# Train the model
history = model.fit(X_train_scaled, 
                    {'department_output': y_department_train, 'attrition_output': y_attrition_train}, 
                    epochs=100, 
                    batch_size=32, 
                    validation_data=(X_test_scaled, {'department_output': y_department_test, 'attrition_output': y_attrition_test}))

Epoch 1/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8686 - attrition_output_loss: 0.3130 - department_output_accuracy: 0.6529 - department_output_loss: 0.7187 - loss: 1.0317 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3482 - val_department_output_accuracy: 0.6667 - val_department_output_loss: 0.7894 - val_loss: 1.1678
Epoch 2/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8687 - attrition_output_loss: 0.3430 - department_output_accuracy: 0.6496 - department_output_loss: 0.7526 - loss: 1.0956 - val_attrition_output_accuracy: 0.8707 - val_attrition_output_loss: 0.3419 - val_department_output_accuracy: 0.6531 - val_department_output_loss: 0.7883 - val_loss: 1.1630
Epoch 3/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8749 - attrition_output_loss: 0.3181 - department_output_accuracy: 0.6434 - department_output_loss: 0.7247 - loss: 1.0428 - val_attrition_output_accuracy: 0.8707 - val_attrition_output_loss: 0.3424 - val_department_output_accuracy: 0.6633 - val_department_output_loss: 0.7914 - val_loss: 1.1664
Epoch 4/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8780 - attrition_output_loss: 0.3208 - department_output_accuracy: 0.6377 - department_output_loss: 0.7340 - loss: 1.0549 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3512 - val_department_output_accuracy: 0.6667 - val_department_output_loss: 0.7991 - val_loss: 1.1810
Epoch 5/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8655 - attrition_output_loss: 0.3518 - department_output_accuracy: 0.6517 - department_output_loss: 0.7407 - loss: 1.0925 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3456 - val_department_output_accuracy: 0.6633 - val_department_output_loss: 0.8004 - val_loss: 1.1797
Epoch 6/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8675 - attrition_output_loss: 0.3343 - department_output_accuracy: 0.6755 - department_output_loss: 0.7181 - loss: 1.0525 - val_attrition_output_accuracy: 0.8810 - val_attrition_output_loss: 0.3608 - val_department_output_accuracy: 0.6190 - val_department_output_loss: 0.8010 - val_loss: 1.1922
Epoch 7/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8787 - attrition_output_loss: 0.3098 - department_output_accuracy: 0.6556 - department_output_loss: 0.7252 - loss: 1.0351 - val_attrition_output_accuracy: 0.8810 - val_attrition_output_loss: 0.3617 - val_department_output_accuracy: 0.6531 - val_department_output_loss: 0.8027 - val_loss: 1.1921
Epoch 8/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8833 - attrition_output_loss: 0.3214 - department_output_accuracy: 0.6671 - department_output_loss: 0.7167 - loss: 1.0381 - val_attrition_output_accuracy: 0.8810 - val_attrition_output_loss: 0.3580 - val_department_output_accuracy: 0.6293 - val_department_output_loss: 0.8011 - val_loss: 1.1907
Epoch 9/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8683 - attrition_output_loss: 0.3233 - department_output_accuracy: 0.6704 - department_output_loss: 0.6971 - loss: 1.0204 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3524 - val_department_output_accuracy: 0.6599 - val_department_output_loss: 0.8097 - val_loss: 1.1959
Epoch 10/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8631 - attrition_output_loss: 0.3453 - department_output_accuracy: 0.6648 - department_output_loss: 0.7080 - loss: 1.0532 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3590 - val_department_output_accuracy: 0.6599 - val_department_output_loss: 0.8107 - val_loss: 1.2020
Epoch 11/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8922 - attrition_output_loss: 0.2820 - department_output_accuracy: 0.6819 - department_output_loss: 0.6739 - loss: 0.9559 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3636 - val_department_output_accuracy: 0.6293 - val_department_output_loss: 0.8081 - val_loss: 1.2034
Epoch 12/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8889 - attrition_output_loss: 0.3051 - department_output_accuracy: 0.6607 - department_output_loss: 0.7334 - loss: 1.0384 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3622 - val_department_output_accuracy: 0.6156 - val_department_output_loss: 0.8147 - val_loss: 1.2109
Epoch 13/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8835 - attrition_output_loss: 0.2883 - department_output_accuracy: 0.6853 - department_output_loss: 0.6998 - loss: 0.9880 - val_attrition_output_accuracy: 0.8776 - val_attrition_output_loss: 0.3663 - val_department_output_accuracy: 0.6429 - val_department_output_loss: 0.8147 - val_loss: 1.2151
Epoch 14/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8794 - attrition_output_loss: 0.2988 - department_output_accuracy: 0.6740 - department_output_loss: 0.7095 - loss: 1.0084 - val_attrition_output_accuracy: 0.8741 - val_attrition_output_loss: 0.3661 - val_department_output_accuracy: 0.6667 - val_department_output_loss: 0.8361 - val_loss: 1.2396
Epoch 15/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8852 - attrition_output_loss: 0.2811 - department_output_accuracy: 0.6763 - department_output_loss: 0.7031 - loss: 0.9842 - val_attrition_output_accuracy: 0.8810 - val_attrition_output_loss: 0.3704 - val_department_output_accuracy: 0.6633 - val_department_output_loss: 0.8256 - val_loss: 1.2299
Epoch 16/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8917 - attrition_output_loss: 0.2881 - department_output_accuracy: 0.6849 - department_output_loss: 0.6652 - loss: 0.9534 - val_attrition_output_accuracy: 0.8707 - val_attrition_output_loss: 0.3787 - val_department_output_accuracy: 0.6224 - val_department_output_loss: 0.8249 - val_loss: 1.2368
Epoch 17/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8857 - attrition_output_loss: 0.2848 - department_output_accuracy: 0.7016 - department_output_loss: 0.6681 - loss: 0.9529 - val_attrition_output_accuracy: 0.8707 - val_attrition_output_loss: 0.3771 - val_department_output_accuracy: 0.6565 - val_department_output_loss: 0.8292 - val_loss: 1.2419
Epoch 18/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8783 - attrition_output_loss: 0.3011 - department_output_accuracy: 0.6769 - department_output_loss: 0.6721 - loss: 0.9732 - val_attrition_output_accuracy: 0.8673 - val_attrition_output_loss: 0.3815 - val_department_output_accuracy: 0.6190 - val_department_output_loss: 0.8341 - val_loss: 1.2488
Epoch 19/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8868 - attrition_output_loss: 0.2917 - department_output_accuracy: 0.6847 - department_output_loss: 0.6663 - loss: 0.9580 - val_attrition_output_accuracy: 0.8673 - val_attrition_output_loss: 0.3903 - val_department_output_accuracy: 0.6531 - val_department_output_loss: 0.8453 - val_loss: 1.2744
Epoch 20/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8898 - attrition_output_loss: 0.3014 - department_output_accuracy: 0.6803 - department_output_loss: 0.6704 - loss: 0.9718 - val_attrition_output_accuracy: 0.8673 - val_attrition_output_loss: 0.3879 - val_department_output_accuracy: 0.6156 - val_department_output_loss: 0.8396 - val_loss: 1.2669
Epoch 21/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8873 - attrition_output_loss: 0.2872 - department_output_accuracy: 0.6915 - department_output_loss: 0.6581 - loss: 0.9454 - val_attrition_output_accuracy: 0.8605 - val_attrition_output_loss: 0.3898 - val_department_output_accuracy: 0.6224 - val_department_output_loss: 0.8459 - val_loss: 1.2749
Epoch 22/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8863 - attrition_output_loss: 0.2735 - department_output_accuracy: 0.7054 - department_output_loss: 0.6492 - loss: 0.9226 - val_attrition_output_accuracy: 0.8537 - val_attrition_output_loss: 0.4095 - val_department_output_accuracy: 0.5680 - val_department_output_loss: 0.8537 - val_loss: 1.3008
Epoch 23/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9052 - attrition_output_loss: 0.2545 - department_output_accuracy: 0.7094 - department_output_loss: 0.6412 - loss: 0.8958 - val_attrition_output_accuracy: 0.8571 - val_attrition_output_loss: 0.3958 - val_department_output_accuracy: 0.6122 - val_department_output_loss: 0.8485 - val_loss: 1.2793
Epoch 24/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8902 - attrition_output_loss: 0.2748 - department_output_accuracy: 0.7176 - department_output_loss: 0.6332 - loss: 0.9080 - val_attrition_output_accuracy: 0.8707 - val_attrition_output_loss: 0.3887 - val_department_output_accuracy: 0.6395 - val_department_output_loss: 0.8559 - val_loss: 1.2849
Epoch 25/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8879 - attrition_output_loss: 0.2842 - department_output_accuracy: 0.6989 - department_output_loss: 0.6426 - loss: 0.9266 - val_attrition_output_accuracy: 0.8639 - val_attrition_output_loss: 0.3901 - val_department_output_accuracy: 0.6327 - val_department_output_loss: 0.8609 - val_loss: 1.2925
Epoch 26/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8962 - attrition_output_loss: 0.2669 - department_output_accuracy: 0.7085 - department_output_loss: 0.6338 - loss: 0.9007 - val_attrition_output_accuracy: 0.8673 - val_attrition_output_loss: 0.3928 - val_department_output_accuracy: 0.5782 - val_department_output_loss: 0.8633 - val_loss: 1.2947
Epoch 27/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8920 - attrition_output_loss: 0.2586 - department_output_accuracy: 0.7196 - department_output_loss: 0.6153 - loss: 0.8738 - val_attrition_output_accuracy: 0.8707 - val_attrition_output_loss: 0.3917 - val_department_output_accuracy: 0.6259 - val_department_output_loss: 0.8770 - val_loss: 1.3159
Epoch 28/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8804 - attrition_output_loss: 0.2889 - department_output_accuracy: 0.6961 - department_output_loss: 0.6287 - loss: 0.9177 - val_attrition_output_accuracy: 0.8605 - val_attrition_output_loss: 0.3924 - val_department_output_accuracy: 0.6395 - val_department_output_loss: 0.8723 - val_loss: 1.3061
Epoch 29/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9089 - attrition_output_loss: 0.2358 - department_output_accuracy: 0.7150 - department_output_loss: 0.6192 - loss: 0.8550 - val_attrition_output_accuracy: 0.8537 - val_attrition_output_loss: 0.4080 - val_department_output_accuracy: 0.5748 - val_department_output_loss: 0.8902 - val_loss: 1.3430
Epoch 30/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8960 - attrition_output_loss: 0.2656 - department_output_accuracy: 0.7469 - department_output_loss: 0.6034 - loss: 0.8689 - val_attrition_output_accuracy: 0.8673 - val_attrition_output_loss: 0.4012 - val_department_output_accuracy: 0.5884 - val_department_output_loss: 0.8773 - val_loss: 1.3183
Epoch 31/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8924 - attrition_output_loss: 0.2600 - department_output_accuracy: 0.7452 - department_output_loss: 0.6064 - loss: 0.8664 - val_attrition_output_accuracy: 0.8571 - val_attrition_output_loss: 0.4108 - val_department_output_accuracy: 0.5782 - val_department_output_loss: 0.8912 - val_loss: 1.3421
Epoch 32/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8960 - attrition_output_loss: 0.2751 - department_output_accuracy: 0.7435 - department_output_loss: 0.5918 - loss: 0.8669 - val_attrition_output_accuracy: 0.8537 - val_attrition_output_loss: 0.4034 - val_department_output_accuracy: 0.5408 - val_department_output_loss: 0.8975 - val_loss: 1.3413
Epoch 33/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8957 - attrition_output_loss: 0.2646 - department_output_accuracy: 0.7451 - department_output_loss: 0.5920 - loss: 0.8566 - val_attrition_output_accuracy: 0.8537 - val_attrition_output_loss: 0.4105 - val_department_output_accuracy: 0.5612 - val_department_output_loss: 0.9012 - val_loss: 1.3539
Epoch 34/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9019 - attrition_output_loss: 0.2535 - department_output_accuracy: 0.7397 - department_output_loss: 0.6135 - loss: 0.8671 - val_attrition_output_accuracy: 0.8435 - val_attrition_output_loss: 0.4126 - val_department_output_accuracy: 0.5170 - val_department_output_loss: 0.9352 - val_loss: 1.3926
Epoch 35/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9017 - attrition_output_loss: 0.2495 - department_output_accuracy: 0.7516 - department_output_loss: 0.5862 - loss: 0.8356 - val_attrition_output_accuracy: 0.8401 - val_attrition_output_loss: 0.4184 - val_department_output_accuracy: 0.5544 - val_department_output_loss: 0.9236 - val_loss: 1.3850
Epoch 36/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9064 - attrition_output_loss: 0.2304 - department_output_accuracy: 0.7598 - department_output_loss: 0.5780 - loss: 0.8084 - val_attrition_output_accuracy: 0.8503 - val_attrition_output_loss: 0.4283 - val_department_output_accuracy: 0.5884 - val_department_output_loss: 0.9152 - val_loss: 1.3908
Epoch 37/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9032 - attrition_output_loss: 0.2462 - department_output_accuracy: 0.7533 - department_output_loss: 0.5688 - loss: 0.8149 - val_attrition_output_accuracy: 0.8503 - val_attrition_output_loss: 0.4177 - val_department_output_accuracy: 0.5680 - val_department_output_loss: 0.9367 - val_loss: 1.4020
Epoch 38/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8888 - attrition_output_loss: 0.2756 - department_output_accuracy: 0.7383 - department_output_loss: 0.5750 - loss: 0.8507 - val_attrition_output_accuracy: 0.8503 - val_attrition_output_loss: 0.4169 - val_department_output_accuracy: 0.5340 - val_department_output_loss: 0.9286 - val_loss: 1.3887
Epoch 39/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8973 - attrition_output_loss: 0.2362 - department_output_accuracy: 0.7589 - department_output_loss: 0.5637 - loss: 0.7999 - val_attrition_output_accuracy: 0.8435 - val_attrition_output_loss: 0.4403 - val_department_output_accuracy: 0.5544 - val_department_output_loss: 0.9637 - val_loss: 1.4490
Epoch 40/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8950 - attrition_output_loss: 0.2605 - department_output_accuracy: 0.7803 - department_output_loss: 0.5467 - loss: 0.8073 - val_attrition_output_accuracy: 0.8435 - val_attrition_output_loss: 0.4359 - val_department_output_accuracy: 0.5578 - val_department_output_loss: 0.9485 - val_loss: 1.4278
Epoch 41/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8979 - attrition_output_loss: 0.2563 - department_output_accuracy: 0.7749 - department_output_loss: 0.5291 - loss: 0.7855 - val_attrition_output_accuracy: 0.8469 - val_attrition_output_loss: 0.4262 - val_department_output_accuracy: 0.5646 - val_department_output_loss: 0.9688 - val_loss: 1.4456
Epoch 42/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.8988 - attrition_output_loss: 0.2410 - department_output_accuracy: 0.7775 - department_output_loss: 0.5347 - loss: 0.7758 - val_attrition_output_accuracy: 0.8503 - val_attrition_output_loss: 0.4281 - val_department_output_accuracy: 0.5476 - val_department_output_loss: 0.9786 - val_loss: 1.4642
Epoch 43/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.9228 - attrition_output_loss: 0.2194 - department_output_accuracy: 0.7694 - department_output_loss: 0.5522 - loss: 0.7716 - val_attrition_output_accuracy: 0.8435 - val_attrition_output_loss: 0.4464 - val_department_output_accuracy: 0.5544 - val_department_output_loss: 0.9848 - val_loss: 1.4767
Epoch 44/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9030 - attrition_output_loss: 0.2480 - department_output_accuracy: 0.7880 - department_output_loss: 0.5166 - loss: 0.7646 - val_attrition_output_accuracy: 0.8435 - val_attrition_output_loss: 0.4362 - val_department_output_accuracy: 0.5408 - val_department_output_loss: 0.9945 - val_loss: 1.4869
Epoch 45/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.8939 - attrition_output_loss: 0.2473 - department_output_accuracy: 0.7825 - department_output_loss: 0.5183 - loss: 0.7656 - val_attrition_output_accuracy: 0.8435 - val_attrition_output_loss: 0.4453 - val_department_output_accuracy: 0.5578 - val_department_output_loss: 1.0075 - val_loss: 1.5107
Epoch 46/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9031 - attrition_output_loss: 0.2371 - department_output_accuracy: 0.7752 - department_output_loss: 0.5267 - loss: 0.7638 - val_attrition_output_accuracy: 0.8401 - val_attrition_output_loss: 0.4690 - val_department_output_accuracy: 0.5408 - val_department_output_loss: 1.0013 - val_loss: 1.5143
Epoch 47/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9189 - attrition_output_loss: 0.2209 - department_output_accuracy: 0.7946 - department_output_loss: 0.5163 - loss: 0.7372 - val_attrition_output_accuracy: 0.8401 - val_attrition_output_loss: 0.4693 - val_department_output_accuracy: 0.5476 - val_department_output_loss: 1.0240 - val_loss: 1.5390
Epoch 48/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9158 - attrition_output_loss: 0.2308 - department_output_accuracy: 0.8044 - department_output_loss: 0.4987 - loss: 0.7295 - val_attrition_output_accuracy: 0.8537 - val_attrition_output_loss: 0.4631 - val_department_output_accuracy: 0.5612 - val_department_output_loss: 1.0249 - val_loss: 1.5400
Epoch 49/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9068 - attrition_output_loss: 0.2205 - department_output_accuracy: 0.7842 - department_output_loss: 0.5320 - loss: 0.7525 - val_attrition_output_accuracy: 0.8503 - val_attrition_output_loss: 0.4571 - val_department_output_accuracy: 0.5646 - val_department_output_loss: 1.0292 - val_loss: 1.5394
Epoch 50/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9123 - attrition_output_loss: 0.2118 - department_output_accuracy: 0.8057 - department_output_loss: 0.5114 - loss: 0.7232 - val_attrition_output_accuracy: 0.8401 - val_attrition_output_loss: 0.4615 - val_department_output_accuracy: 0.5748 - val_department_output_loss: 1.0637 - val_loss: 1.5858
Epoch 51/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - attrition_output_accuracy: 0.9235 - attrition_output_loss: 0.2099 - department_output_accuracy: 0.8123 - department_output_loss: 0.5064 - loss: 0.7164 - val_attrition_output_accuracy: 0.8503 - val_attrition_output_loss: 0.4698 - val_department_output_accuracy: 0.5714 - val_department_output_loss: 1.0496 - val_loss: 1.5817
Epoch 52/100
37/37 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - attrition_output_accuracy: 0.9151 - attrition_output_loss: 0.2142 - department_output_accuracy: 0.8205 - department_output_loss: 0.4906 - loss: 0.7048 - val_attrition_output_accuracy: 0.8503 - val_attrition_output_loss: 0.4613 - val_department_output_accuracy: 0.5238 - val_department_output_loss: 1.0758 - val_loss: 1.6036
Epoch 53/100

In [78]:
# Evaluate the model with the testing data
test_results = model.evaluate(X_test_scaled, 
                                           {'department_output': y_department_test, 'attrition_output': y_attrition_test})

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - attrition_output_accuracy: 0.8293 - attrition_output_loss: 0.7177 - department_output_accuracy: 0.5160 - department_output_loss: 1.7417 - loss: 2.4811

In [81]:
test_results_dict = dict(zip(model.metrics_names, test_results))
test_results_dict

{'loss': 2.303149461746216,
 'compile_metrics': 1.5129344463348389,
 'department_output_loss': 0.6711121797561646,
 'attrition_output_loss': 0.8163265585899353}

In [82]:
# Print the accuracy for both department and attrition
#print(f"Department Accuracy: {test_results[3]:.4f}")
#print(f"Attrition Accuracy: {test_results[1]:.4f}")

# Summary

In the provided space below, briefly answer the following questions.

1. Is accuracy the best metric to use on this data? Why or why not?

2. What activation functions did you choose for your output layers, and why?

3. Can you name a few ways that this model might be improved?

YOUR ANSWERS HERE

1. Accuracy can be used but it can create a possible imbalance of the data. F1 may be a better metric. 
2. Sigmoid activation function was used and softmax could also be used. 
3. More information added as columns such as previous employment tenures for each employee.